baseURL = "https://example.com/"
languageCode = "en-us"
title = "Athena Hugo Theme"
theme = "../.."
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "A clean and readable Hugo theme (port of https://github.com/broccolini/athena)"
dateform = "Jan 2, 2006"
disable_next_prev = true
github_repo = "mnoronha.com"
github_username = "mtn"
